<a href="https://colab.research.google.com/github/Songeuiseob/Coursera_BigData/blob/main/Bigdata_exercies1_R.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a <- 1
a

[1] 1

In [ ]:
str1 <- "2022-04-09"
str2 <- "2022-06-25"
x <- as.Date(str1)
y <- as.Date(str2)
y - x

Time difference of 77 days

In [ ]:
# names() 함수를 이용한 slicing
x <- c(100, 200, 300)
names(x) <- c("a", "b", "c")
x["b"]

b 
200

In [ ]:
# 벡터의 집합 연산
x1 <- c(10, 20, 30, 40)
x2 <- c(30, 40, 50, 60)
x3 <- c(40, 30, 20, 10)
union(x1, x2)           # 합집합
intersect(x1, x2)       # 교집합   
setdiff(x1, x2)         # 차집합 x1 - x2
setequal(x1, x2)        # x1, x2가 동일하면 TRUE, 아니면 FALSE 반환
setequal(x1, x3)

[1] 10 20 30 40 50 60

[1] 30 40

[1] 10 20

[1] FALSE

[1] TRUE

In [ ]:
# R의 기초통계함수
# 표준편차 : sd(x)
# 분산 : var(x)
# 공분산 : cov(x, y)
# 상관계수 : coef(x, y)
# 벡터의 길이 : length(x)
x <- c(10, 20, 30, 40, 50)
y <- c(1, 2, 3, 4, 5)
sd(c(x, y))
var(c(x, y))
cov(x, y)

[1] 17.74041

[1] 314.7222

[1] 25

In [ ]:
# 행렬(Matrix)
# 행렬 생성 : matrix()함수 이용, matrix(data, nrow, ncol)
x <- c(1:20)
x <- matrix(x, 5, 4)
x                       

[,1] [,2] [,3] [,4]
[1,] 1     6   11   16  
[2,] 2     7   12   17  
[3,] 3     8   13   18  
[4,] 4     9   14   19  
[5,] 5    10   15   20

In [ ]:
# matrix는 1행 1열, 1행 2열, 1행 3열의 순서로 채워짐. byrow = T 옵션을 사용하면 행기준으로 생상
x <- c(1:20)
x <- matrix(x, 5, 4, byrow = T)
x  

[,1] [,2] [,3] [,4]
[1,]  1    2    3    4  
[2,]  5    6    7    8  
[3,]  9   10   11   12  
[4,] 13   14   15   16  
[5,] 17   18   19   20

In [ ]:
# 행렬 데이터의 slicing
x <- matrix(1:20, 5, 4)
x[1, 3]                 # x의 1행 3열 값 반환

[1] 11

In [ ]:
# 행과 열의 범위 지정
x[2:4, 3:4]             # 2행에서 4행에서 3, 4열만 반환

[,1] [,2]
[1,] 12   17  
[2,] 13   18  
[3,] 14   19

In [ ]:
# (-)부호를 사용하여 해당 행 또는 열을 제외한 나머지 선택
x[-3, ]

[,1] [,2] [,3] [,4]
[1,] 1     6   11   16  
[2,] 2     7   12   17  
[3,] 4     9   14   19  
[4,] 5    10   15   20

In [ ]:
# 행렬의 연산
# 행렬곱 : %*%
# 전치행렬 : t()
# 역행렬 : solve()
# 행렬의 차원 : dim()
x <- matrix(1:4, 2, 2)
x
x %*% x

[,1] [,2]
[1,] 1    3   
[2,] 2    4

[,1] [,2]
[1,]  7   15  
[2,] 10   22

In [ ]:
# 데이터프레임의 생성
# 열에 해당하는 벡터를 먼저 정의하고 합쳐서 데이터프레임으로 정의

x1 <- c("01", "02", "03", "04", "05")
x2 <- c("사과", "배", "감", "귤", "바나나")
x3 <- c(100, 200, 300, 400, 500)
x4 <- c(10, 25, 30, 20, 15)

In [ ]:
df = data.frame(과일번호 = x1, 과일명 = x2, 가격 = x3, 수량 = x4)
df

과일번호 과일명 가격 수량
1 01       사과   100  10  
2 02       배     200  25  
3 03       감     300  30  
4 04       귤     400  20  
5 05       바나나 500  15

In [ ]:
# 데이터프레임의 구조 확인
# str() 
str(df)

'data.frame':	5 obs. of  4 variables:
 $ 과일번호: chr  "01" "02" "03" "04" ...
 $ 과일명  : chr  "사과" "배" "감" "귤" ...
 $ 가격    : num  100 200 300 400 500
 $ 수량    : num  10 25 30 20 15


In [ ]:
# 데이터프레임 데이터 선택하기
# data.frame[행, 렬] 또는 data.frames$변수 사용
# 행번호 또는 열번호 생략 시 행전체 또는 열전체 데이터를 선택
df[2, 2]
df$"과일명"
df[3, ]
df[, "가격"]

[1] "배"

[1] "사과"   "배"     "감"     "귤"     "바나나"

과일번호 과일명 가격 수량
3 03       감     300  30

[1] 100 200 300 400 500

In [ ]:
# 여러건 선택
df[c(1, 3), ]
df[c(1, 2), c(3, 4)]

# 범위 선택
df[1:3, 1:2]

과일번호 과일명 가격 수량
1 01       사과   100  10  
3 03       감     300  30

가격 수량
1 100  10  
2 200  25

과일번호 과일명
1 01       사과  
2 02       배    
3 03       감

In [ ]:
# 데이터프레임 상위(하위) n개 선택
head(df, n = 3)
tail(df, n = 2)

과일번호 과일명 가격 수량
1 01       사과   100  10  
2 02       배     200  25  
3 03       감     300  30

과일번호 과일명 가격 수량
4 04       귤     400  20  
5 05       바나나 500  15

In [ ]:
# 조건에 맞는 행 선택
subset(df, 가격 >= 250)
subset(df, 과일명 == "바나나")

과일번호 과일명 가격 수량
3 03       감     300  30  
4 04       귤     400  20  
5 05       바나나 500  15

과일번호 과일명 가격 수량
5 05       바나나 500  15

In [ ]:
# 조건에 맞는 행 중 특정 열만 가져오기(select 옵션 사용)
subset(df, 가격 >= 250, select = c("가격", "수량"))

가격 수량
3 300  30  
4 400  20  
5 500  15

In [17]:
# rbind : 두 개 이상의 데이터프레임을 행으로 결합(열의 개수와 이름이 동일해야 함)
# cbind : 두 개 이상의 데이터프레임을 열로 결합(행의 개수가 동일해야 함)
df1 <- head(df, n = 2)
df2 <- tail(df, n = 2)
df1
df2

df3 <-rbind(df1, df2)
df3

df4 <- cbind(df1, df2)
df4

과일번호 과일명 가격 수량
1 01       사과   100  10  
2 02       배     200  25

과일번호 과일명 가격 수량
4 04       귤     400  20  
5 05       바나나 500  15

과일번호 과일명 가격 수량
1 01       사과   100  10  
2 02       배     200  25  
4 04       귤     400  20  
5 05       바나나 500  15

과일번호 과일명 가격 수량 과일번호 과일명 가격 수량
1 01       사과   100  10   04       귤     400  20  
2 02       배     200  25   05       바나나 500  15

In [18]:
# 리스트 : 벡터, 데이터프레임, 배열, 함수 등과 같은 R의 모든 객체를 담을 수 있는 데이터 구조
# (키, 값)의 형태로 데이터를 저장
# 각 객체의 이름은 '키' 자리에 입력하며, '키'가 없는 경우 [[1]], [[2]], [[3]]의 순으로 이름이 부여됨

# 리스트 생성 : list()
x <- c("사과", "배", "감", "귤", "바나나") # 벡터 생성
x

y1 <- c(10, 20, 30, 40, 50)
y2 <- c(1, 2, 3, 4, 5)
df <- data.frame(y1, y2)  # 데이터프레임 생성
df

list1 <- list(x, df)      # 리스트 생성
list1

[1] "사과"   "배"     "감"     "귤"     "바나나"

y1 y2
1 10 1 
2 20 2 
3 30 3 
4 40 4 
5 50 5

[[1]]
[1] "사과"   "배"     "감"     "귤"     "바나나"

[[2]]
  y1 y2
1 10  1
2 20  2
3 30  3
4 40  4
5 50  5

In [21]:
# 리스트 다루기
# 리스트[n]     # n번째 객체(벡터, 행렬, 데이터프레임 등)를 가져옴
# 리스트$키     # '키'값에 해당하는 원소 출력

x <- c("사과", "배", "감", "귤", "바나나")
y <- c(10:20)

list1 <- list("과일" = x, "숫자" = y)
list1

list1[1]
list1$숫자

$과일
[1] "사과"   "배"     "감"     "귤"     "바나나"

$숫자
 [1] 10 11 12 13 14 15 16 17 18 19 20

$과일
[1] "사과"   "배"     "감"     "귤"     "바나나"

[1] 10 11 12 13 14 15 16 17 18 19 20